FLASK_DEBUG = True  # CHANGE BEFORE DEPLOYMENT
FLASK_THREADED = True

RESTPLUS_VAL = True
RESTPLUS_SWAGGER_EXPANSION = "list"
RESTPLUS_MASK_SWAGGER = False

SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite"
SQLALCHEMY_TRACK_MODS = False
